apiVersion: v1
kind: Secret
metadata:
  name: ore-secrets
type: Opaque
stringData:
  jwt-secret: "change-me-min-32-characters-long-secret"
  # postgresql://user:pass@postgres:5432/ore_ui
  database-url: ""
  seed-admin-password: "admin"
  postgres-password: "change-me"
